topcoder-platform/platform-ui

- src/apps/dev-center/src/dev-center-pages/platform-ui-app/getting-started/GettingStartedGuide.md
https://topcoder.atlassian.net/browse/PM-462
> PM-462 - update urls

- src/apps/onboarding/src/components/InputTextAutoSave/index.tsx
- src/apps/onboarding/src/pages/open-to-work/index.tsx
https://topcoder.atlassian.net/browse/PM-505
The default value for the Bio title and open to work checkbox were not accurate. This fixes that
> PM-505 Fix default values on onboarding form

- src/apps/dev-center/src/dev-center-pages/platform-ui-app/storybook/Storybook.tsx
https://topcoder.atlassian.net/browse/PM-553
- Fixed the breadcrumb url for storybook page in dev center
> PM-553: fix breadcrumb url

- src/libs/core/lib/router/restricted.route.tsx
We change the rolesRequired logic from AND to OR
This allows Admin or Project manager to access the copilots/request route
> PM-579 Change Restricted route logic

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
- src/libs/ui/lib/components/button/base-button/BaseButton.module.scss
- src/libs/ui/lib/components/button/base-button/BaseButton.tsx
Makes the text on buttons responsive
> PM-579 Make buttons in form responsive

- src/apps/admin/src/admin-app.routes.tsx
- src/apps/admin/src/challenge-management/ChallengeManagement.tsx
https://topcoder.atlassian.net/browse/N/A
Fix the routes for the system-admin
> fix system-admin/challenge management routes

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
- src/libs/ui/lib/components/form/form-groups/form-input/input-select-react/InputSelectReact.tsx
- page scrolls to top when errors are present
- Project id should be null for the select component to reset
> PM-579 Reset project when form resets

- src/apps/copilots/src/constants/index.ts
- src/apps/copilots/src/copilots.routes.tsx
- src/apps/copilots/src/models/CopilotRequest.ts
- src/apps/copilots/src/pages/copilot-request-form/index.tsx
- src/apps/copilots/src/pages/copilot-requests/CopilotRequestsPage.module.scss
- src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/CopilotRequestModal.module.scss
- src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/CopilotRequestModal.tsx
- src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/index.ts
- src/apps/copilots/src/pages/copilot-requests/index.tsx
- src/apps/copilots/src/services/copilot-requests.ts
- src/apps/copilots/src/services/projects.ts
- src/libs/shared/lib/utils/url.ts
https://topcoder.atlassian.net/browse/PM-588
- Adds a new page under "/copilot/requests" that lists all current copilot requests
- moved the new copilot request form to "copilots/requests/new"
- added button on the copilot requests page for "new copilot request"
> PM-588 - copilot requests page

- src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/CopilotRequestModal.tsx
- src/apps/copilots/src/services/projects.ts
- src/libs/shared/lib/utils/url.ts
https://topcoder.atlassian.net/browse/PM-588
Fix the way we fetch the projects by id
> PM-588 - fix project fetch

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
> Fix resending request

- src/apps/copilots/src/constants/index.ts
Remove extra project types and consolidate into data science
> PM-579 Align project types to endpoint

- src/apps/copilots/src/models/CopilotRequest.ts
- src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/CopilotRequestModal.tsx
- src/apps/copilots/src/pages/copilot-requests/index.tsx
https://topcoder.atlassian.net/browse/PM-588
Handles minor QA feedback
> PM-588 qa feedback

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
> Display api errors

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
New errors are required on form.
> PM-579 Error handling on form

- src/apps/copilots/src/copilots.routes.tsx
- src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx
- src/apps/copilots/src/pages/copilot-opportunity-details/styles.module.scss
- src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx
- src/apps/copilots/src/services/copilot-opportunities.ts
https://topcoder.atlassian.net/browse/PM-590
> PM-590 Copilot opportunity details page

- src/apps/admin/src/lib/components/ReviewerList/ReviewerList.tsx
- src/apps/admin/src/review-management/ManageReviewerPage/ManageReviewerPage.tsx
Challenge https://www.topcoder.com/challenges/73034874-82a3-43a2-b835-f2f7d89f8f8c?tab=details
> Review Application Bug Fix

- src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx
https://topcoder.atlassian.net/browse/PM-1064
> PM- 1064 Fix admin role var

- src/apps/copilots/src/pages/copilot-opportunity-list/styles.module.scss
https://topcoder.atlassian.net/browse/PM-589
> PM-589 Fix white space for status

- src/apps/wallet/src/home/tabs/winnings/WinningsTab.tsx
https://topcoder.atlassian.net/browse/
> fix for wallet: status filter

- src/apps/wallet-admin/src/lib/components/payments-table/PaymentTable.tsx
https://topcoder.atlassian.net/browse/PM-1196
> fix spacing in wallet-admin table

- src/apps/wallet/src/home/tabs/home/HomeTab.tsx
- src/apps/wallet/src/lib/models/WalletDetails.ts
https://topcoder.atlassian.net/browse/OM-1345
add banner in wallet homepage for ID verification
> PM-1345 trolley trust module

- src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx
https://topcoder.atlassian.net/browse/PM-1373
- sorting for duration column
> fix(PM-1373): sorting for duration column

- src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplicationAction.tsx
https://topcoder.atlassian.net/browse/PM-1469
- added hover actions for copilot application icons
> fix(PM-1469): added hover actions for application icons

- src/apps/copilots/src/pages/copilot-opportunity-details/apply-opportunity-modal/styles.module.scss
- src/apps/copilots/src/pages/copilot-opportunity-details/styles.module.scss
- src/apps/copilots/src/pages/copilot-opportunity-details/tabs/opportunity-details/styles.module.scss
https://topcoder.atlassian.net/browse/PM-1320
- Fixed layout issues in copilot opportunity details page
> fix(PM-1320): Layout issues in copilot opportunity details page

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
https://topcoder.atlassian.net/browse/PM-1498
> Update validation for copilot opportunity title

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
https://topcoder.atlassian.net/browse/PM-1499
> PM-1499 - update copilot form request

- src/apps/copilots/src/pages/copilot-requests/CopilotRequestsPage.module.scss
- src/apps/copilots/src/pages/copilot-requests/index.tsx
https://topcoder.atlassian.net/browse/PM-1499
> PM-1499 - make sure canceled & fulfilled requests are not editable

- src/apps/copilots/src/pages/copilot-request-form/index.tsx
https://topcoder.atlassian.net/browse/PM-1527
Fix toast message
> Fix toast message for Edit copilot requests on

- src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx
https://topcoder.atlassian.net/browse/PM-1532
Fixes sorting on title. The property name wasn't changed when title was introduced
> PM-1532 Fix sorting on title

- src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/AlreadyMemberModal.tsx
https://topcoder.atlassian.net/browse/PM-1506
- reverted back to old code
> fix(PM-1506): revert back to old code

- src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx
https://topcoder.atlassian.net/browse/PM-1555
Payments is not sortable now because it's a free text column
> PM-1555 Remove sorting from Payment column

- src/libs/ui/lib/components/tabs-navbar/TabsNavbar.tsx
https://topcoder.atlassian.net/browse/PM-1529
Show the dropdown icon only if there's more than one tabs in mobile view
> Remove dropdown icon if not more than one in list

- src/apps/review/src/review-app.routes.tsx
- src/libs/shared/lib/containers/auth/restricted-page/RestrictedPage.module.scss
https://topcoder.atlassian.net/browse/PM-1502
Adds auth step before routing to scorecards
Only admins are allowed to see the page.
> PM-1502 Add auth before routing

- src/apps/review/src/lib/components/TableScorecards/TableScorecards.module.scss
- src/apps/review/src/pages/scorecards/ScorecardsListPage/ScorecardsListPage.tsx
https://topcoder.atlassian.net/browse/PM-1505
> PM-1505 - Clone scorecard fix

- src/apps/review/src/pages/scorecards/EditScorecardPage/EditScorecardPage.module.scss
https://topcoder.atlassian.net/browse/PM-1504
> Fix error width

- src/apps/review/src/pages/scorecards/EditScorecardPage/components/ScorecardInfoForm.tsx
https://topcoder.atlassian.net/browse/PM-1504
> PM-1504 - scorecard: Make category options dependent on project type

- src/apps/review/src/pages/scorecards/EditScorecardPage/EditScorecardPage.tsx
https://topcoder.atlassian.net/browse/PM-1504
> PM-1504 - redirect to view scorecard

- src/apps/review/src/pages/scorecards/ViewScorecardPage/ViewScorecardPage.tsx
https://topcoder.atlassian.net/browse/PM-1503
- removed breadcrumb for non admin users
> fix(PM-1503): removed breadcrumb for non admin users

- src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx
- src/apps/copilots/src/pages/copilot-opportunity-details/tabs/config/copilot-details-tabs-config.ts
https://topcoder.atlassian.net/browse/PM-1612
Fix Application tab view - allow all users to view it
> PM-1612 Fix Applications tab view

- src/apps/copilots/src/services/copilot-opportunities.ts
https://topcoder.atlassian.net/browse/PM-1836
- Fixed undefined error when getting Project Name
> fix(PM-1836): project object optional

- src/apps/review/src/pages/scorecards/EditScorecardPage/components/ScorecardInfoForm.tsx
https://topcoder.atlassian.net/browse/PM-1805
- Category not saved properly
> fix(PM-1805): Category not saved properly

- src/apps/onboarding/src/components/modal-add-education/index.tsx
- src/apps/onboarding/src/components/modal-add-work/index.tsx
- src/apps/onboarding/src/models/EducationInfo.ts
- src/apps/onboarding/src/models/WorkInfo.ts
- src/apps/onboarding/src/pages/educations/index.tsx
- src/apps/onboarding/src/pages/works/index.tsx
- src/apps/onboarding/src/redux/actions/member.ts
https://topcoder.atlassian.net/browse/PM-2076
- V6 API returns data a bit differently than v5 so had to make some changes on UI to work with it.
> fix(PM-2076): Issues with the already existing users with data in onboarding

- src/apps/onboarding/src/redux/actions/member.ts
https://topcoder.atlassian.net/browse/PM-2074
- Personalization step was broken because of undefined exception.
> fix(PM-2074): check for undefined in onboarding flow
