topcoder-platform/platform-ui

src/apps/onboarding/src/components/InputTextAutoSave/index.tsx, src/apps/onboarding/src/redux/reducers/member.ts
https://topcoder.atlassian.net/browse/PM-505
Fixes QA feedback
=> PM-505 Fix QA feedback

src/apps/copilots/README.md, src/apps/copilots/index.ts, src/apps/copilots/src/CopilotsApp.tsx, src/apps/copilots/src/constants/index.ts, src/apps/copilots/src/copilots.routes.tsx, src/apps/copilots/src/index.ts, src/apps/copilots/src/models/CopilotRequest.ts, src/apps/copilots/src/models/Project.ts, src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/apps/copilots/src/pages/copilot-request-form/styles.module.scss, src/apps/copilots/src/services/projects.ts, src/apps/platform/src/platform.routes.tsx, src/config/constants.ts, src/libs/core/lib/profile/profile-functions/profile-factory/user-role.enum.ts, src/libs/ui/lib/components/button/base-button/BaseButton.module.scss, src/libs/ui/lib/components/button/base-button/BaseButton.tsx
This PR includes the new copilot app, the copilot request form that's populated with projects and skills to choose from
This is missing the integration to the API call to save the copilot request.
=> PM-579 Add copilot request UI

src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/apps/copilots/src/services/projects.ts, src/libs/ui/lib/components/form/form-groups/form-input/input-select-react/InputSelectReact.tsx
Changes Project input to searchable input
Fixes other issues reported by QA
=> PM-579 QR feedback on copilot request form

src/apps/admin/src/challenge-management/ManageUserPage/ManageUserPage.tsx, src/apps/admin/src/config/index.config.ts, src/apps/admin/src/lib/components/ChallengeFilters/ChallengeFilters.tsx, src/apps/admin/src/lib/components/ChallengeUserFilters/ChallengeUserFilters.tsx, src/apps/admin/src/lib/components/common/Pagination/Pagination.tsx, src/apps/admin/src/lib/services/challenge-management.service.ts, src/apps/admin/src/lib/services/user.service.ts, src/apps/admin/src/lib/utils/api.ts
Submission for challenge https://www.topcoder.com/challenges/0eaa6623-4a42-4e33-abd2-d8df3ff65412?tab=details
=> Topcoder Admin App - Misc Bug Fix

src/apps/wallet/src/home/tabs/WalletTabs.tsx, src/apps/wallet/src/home/tabs/config/wallet-tabs-config.ts, src/apps/wallet/src/home/tabs/payout/PayoutTab.module.scss, src/apps/wallet/src/home/tabs/payout/PayoutTab.tsx, src/apps/wallet/src/home/tabs/payout/index.ts, src/apps/wallet/src/lib/services/wallet.ts, src/config/environments/default.env.ts, src/config/environments/global-config.model.ts, src/libs/ui/lib/components/tabs-navbar/TabsNavbar.tsx, src/libs/ui/lib/components/tabs-navbar/tabs-nav-item.model.ts
https://topcoder.atlassian.net/browse/PM-1098
Adds Payout tab, renders the trolley portal widget
=> PM-1098 payout tab

src/apps/admin/src/lib/models/MobileTableColumn.model.ts, src/apps/copilots/src/copilots.routes.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-list/styles.module.scss, src/apps/copilots/src/services/copilot-opportunities.ts, src/libs/ui/lib/components/table/Table.tsx, src/libs/ui/lib/components/table/table-column.model.ts, src/libs/ui/lib/components/table/table-functions/table.functions.ts
https://topcoder.atlassian.net/browse/PM-590
Adds start date to the details page:
=> PM-590 Add start date

src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx, src/apps/copilots/src/services/copilot-opportunities.ts
https://topcoder.atlassian.net/browse/PM-589
Add logic to Show load more button only when there is more data to load
=> PM-589 Fix Load more logic

src/apps/wallet-admin/src/home/tabs/payments/PaymentsTab.tsx, src/apps/wallet-admin/src/lib/components/payment-edit/PaymentEdit.tsx, src/apps/wallet-admin/src/lib/components/payment-view/PaymentView.tsx, src/apps/wallet-admin/src/lib/components/payments-table/PaymentTable.tsx, src/apps/wallet-admin/src/lib/models/WinningDetail.ts, src/apps/wallet/src/home/tabs/home/HomeTab.tsx, src/apps/wallet/src/home/tabs/winnings/WinningsTab.tsx, src/apps/wallet/src/lib/components/payments-table/PaymentTable.tsx, src/apps/wallet/src/lib/models/WinningDetail.ts
https://topcoder.atlassian.net/browse/PM-1142
As a side-effect of removing tax-forms, we also removed logic for "netAmount". Tax will get deducted on trolley side, so we're only handling gross amount.
=> PM-1142 reset tax forms

src/apps/admin/src/lib/components/FieldSingleSelect/FieldSingleSelect.tsx, src/apps/admin/src/lib/components/RoleMembersFilters/RoleMembersFilters.tsx, src/apps/admin/src/lib/components/RoleMembersTable/RoleMembersTable.tsx, src/apps/admin/src/lib/components/RolesFilter/RolesFilter.tsx, src/apps/admin/src/lib/components/common/ReactSelectExport.tsx, src/apps/admin/src/lib/components/common/TableMobile/TableMobile.module.scss, src/apps/admin/src/lib/components/common/TableMobile/TableMobile.tsx, src/apps/admin/src/lib/hooks/useManagePermissionRoleMembers.ts, src/apps/admin/src/lib/models/FormRoleMembersFilters.model.ts, src/apps/admin/src/lib/models/FormRolesFilter.type.ts, src/apps/admin/src/lib/models/MobileTableColumn.model.ts, src/apps/admin/src/lib/models/RoleMemberInfo.model.ts, src/apps/admin/src/lib/models/UserRole.model.ts, src/apps/admin/src/lib/utils/validation.ts, src/apps/admin/src/permission-management/PermissionRolesPage/PermissionRolesPage.tsx
Challenge https://www.topcoder.com/challenges/90b9dcd4-24b0-48a5-aae1-12b6158c2cd6
=> Topcoder Admin App - Roles Management Update

src/apps/copilots/src/pages/copilot-requests/index.tsx
https://topcoder.atlassian.net/browse/PM-1157
Only allow Admins and PMs to view the copilot requests page. The api has this check already. This PR only adds the frontend content for when the access is denied.
=> PM-1157 Add fallback content for copilot requests when access denied

src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx, src/libs/ui/lib/components/content-layout/ContentLayout.module.scss, src/libs/ui/lib/components/content-layout/ContentLayout.tsx
https://topcoder.atlassian.net/browse/PM-876
Adds a button that takes user to requests page from the opportunity list page.
=> PM-876 Add a requests button on opportunity feed

src/apps/wallet/src/home/tabs/winnings/WinningsTab.tsx, src/apps/wallet/src/lib/services/wallet.ts
https://topcoder.atlassian.net/browse/PM-1099
Withdrawal endpoint has been updated, rename "paymentIds" to "winningsIds"
=> PM-1099 - updated the withdrawal endpoint

src/apps/admin/src/challenge-management/ChallengeManagementPage/ChallengeManagementPage.tsx, src/apps/admin/src/lib/components/BillingAccountResourcesTable/BillingAccountResourcesTable.tsx, src/apps/admin/src/lib/components/BillingAccountsFilter/BillingAccountsFilter.module.scss, src/apps/admin/src/lib/components/BillingAccountsFilter/BillingAccountsFilter.tsx, src/apps/admin/src/lib/components/ChallengeFilters/ChallengeFilters.module.scss, src/apps/admin/src/lib/components/ChallengeFilters/ChallengeFilters.tsx, src/apps/admin/src/lib/components/ChallengeList/ChallengeList.tsx, src/apps/admin/src/lib/components/ClientsFilter/ClientsFilter.module.scss, src/apps/admin/src/lib/components/ClientsFilter/ClientsFilter.tsx, src/apps/admin/src/lib/components/ReviewSummaryList/ReviewSummaryList.module.scss, src/apps/admin/src/lib/components/ReviewSummaryList/ReviewSummaryList.tsx, src/apps/admin/src/lib/components/UsersFilters/UsersFilters.module.scss, src/apps/admin/src/lib/components/UsersFilters/UsersFilters.tsx, src/config/environments/default.env.ts, src/config/environments/global-config.model.ts, src/config/environments/prod.env.ts
Challenge https://www.topcoder.com/challenges/852b6d05-cacd-427f-a974-99347a67801c?tab=details
=> Topcoder Admin App - Misc Update 0505

.circleci/config.yml, src/apps/copilots/src/models/CopilotApplication.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/styles.module.scss, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/config/copilot-details-tabs-config.ts, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplications.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/index.ts, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/opportunity-details/OpportunityDetails.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/opportunity-details/index.ts, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/opportunity-details/styles.module.scss, src/apps/copilots/src/services/members.ts, src/libs/ui/lib/components/table/Table.tsx, src/libs/ui/lib/components/table/table-row/TableRow.tsx
https://topcoder.atlassian.net/browse/PM-1067
- Added a new tab section in the copilot opportunity details page
- Added Applications as one of the tab in it and it will be shown only to project managers or admins
=> feat(PM-1067): list copilot applications

src/apps/copilots/src/pages/copilot-opportunity-details/apply-opportunity-modal/ApplyOpportunityModal.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/styles.module.scss, src/apps/copilots/src/services/copilot-opportunities.ts, src/libs/shared/lib/utils/text-format.ts, src/libs/ui/lib/components/content-layout/ContentLayout.tsx, src/libs/ui/lib/styles/_modals.scss
https://topcoder.atlassian.net/browse/PM-578
- Fixed QA feedbacks on apply copilot opportunity functionality
=> fix(PM-578): QA feedbacks on apply copilot opportunity functionality

src/apps/admin/src/lib/components/common/Tab/SystemAdminTabs.tsx, src/apps/admin/src/review-management/ManageReviewerPage/ManageReviewerPage.tsx
Original unapprove challenge id is a mock id.
Current fix it, get real challenge id by api
And also fix the tab show when redirecting to manage user page.
=> Fix unapprove challenge id

src/apps/wallet/src/home/tabs/home/HomeTab.tsx, src/apps/wallet/src/home/tabs/winnings/Winnings.module.scss, src/apps/wallet/src/home/tabs/winnings/WinningsTab.tsx, src/apps/wallet/src/lib/components/info-row/InfoRow.module.scss, src/apps/wallet/src/lib/hooks/use-wallet-details.ts, src/apps/wallet/src/lib/models/WalletDetails.ts, src/apps/wallet/src/lib/services/wallet.ts, src/apps/wallet/src/lib/util/index.ts, src/apps/wallet/src/lib/util/null-to-zero.ts
https://topcoder.atlassian.net/browse/PM-1222
show taxes & fees applied to payments
=> PM-1222 - show taxes & fees applied to payments

src/apps/wallet-admin/src/home/tabs/payments/PaymentsTab.tsx, src/apps/wallet-admin/src/lib/components/filter-bar/FilterBar.tsx, src/apps/wallet-admin/src/lib/components/payments-table/PaymentTable.module.scss, src/apps/wallet-admin/src/lib/components/payments-table/PaymentTable.tsx
https://topcoder.atlassian.net/browse/PM-1196
https://topcoder.atlassian.net/browse/PM-1211
https://topcoder.atlassian.net/browse/PM-1195
https://topcoder.atlassian.net/browse/PM-1197
=> minor admin-wallet fixes

src/apps/copilots/src/models/CopilotApplication.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplicationAction.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplications.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/styles.module.scss, src/apps/copilots/src/services/copilot-opportunities.ts
https://topcoder.atlassian.net/browse/PM-580
- Added assign action to applications list
- Integrated with the project service API
=> feat(PM-580): added assign action to applications list

src/apps/copilots/src/models/CopilotApplication.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplicationAction.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplications.tsx
https://topcoder.atlassian.net/browse/PM-580
- show invite button only for active projects
=> fix(PM-580): show invite button only for active projects

src/apps/admin/src/billing-account/BillingAccountNewPage/BillingAccountNewPage.tsx, src/config/environments/default.env.ts, src/config/environments/global-config.model.ts, src/config/environments/prod.env.ts
Admin billing accounts: always set payment_terms_id = 1 when send update
=> Admin billing accounts: always set payment_terms_id = 1 when send update

src/apps/wallet/src/home/tabs/winnings/WinningsTab.tsx, src/apps/wallet/src/lib/components/payments-table/PaymentTable.module.scss, src/apps/wallet/src/lib/components/payments-table/PaymentTable.tsx, src/apps/wallet/src/lib/models/WalletDetails.ts, src/libs/ui/lib/components/tooltip/Tooltip.tsx
https://topcoder.atlassian.net/browse/PM-1278
=> PM-1278 limit withdrawal min

src/apps/copilots/src/copilots.routes.tsx, src/apps/copilots/src/models/CopilotOpportunity.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/apps/copilots/src/services/projects.ts, src/libs/ui/lib/components/form/form-groups/form-input/input-select-react/InputSelectReact.tsx
https://topcoder.atlassian.net/browse/PM-1273
- show apply copilot only for projects where user is not a member
=> fix(PM-1273): show apply copilot only for projects where user is not a member

src/apps/wallet-admin/src/home/tabs/payments/PaymentsTab.tsx, src/apps/wallet-admin/src/lib/components/payment-edit/PaymentEdit.tsx
https://topcoder.atlassian.net/browse/PM-1304 - Allow for updating the payment description in the wallet-admin
=> PM-1304 - allow admin to update payment description

src/apps/copilots/src/models/CopilotOpportunity.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx
https://topcoder.atlassian.net/browse/PM-1273
- removed members from copilot response and use canApplyAsCopilot
=> fix(PM-1273): remove members from copilot response and use canApplyAsCopilot

src/apps/wallet/src/home/tabs/winnings/ConfirmPayment.modal.tsx, src/apps/wallet/src/home/tabs/winnings/WinningsTab.tsx, src/apps/wallet/src/lib/components/otp-modal/OtpModal.tsx, src/apps/wallet/src/lib/components/otp-modal/index.ts, src/apps/wallet/src/lib/components/otp-modal/use-otp-modal.tsx, src/apps/wallet/src/lib/models/ApiResponse.ts, src/apps/wallet/src/lib/models/ConfirmFlowData.ts, src/apps/wallet/src/lib/services/wallet.ts, src/libs/ui/lib/components/modals/confirm/ConfirmModal.tsx
https://topcoder.atlassian.net/browse/PM-1374
Added OTP requirement to withdraw payments
=> PM-1374 - require otp when withdrawing

src/apps/copilots/src/pages/copilot-opportunity-details/apply-opportunity-modal/ApplyOpportunityModal.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/styles.module.scss, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplicationAction.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/opportunity-details/OpportunityDetails.tsx, src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx, src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/apps/copilots/src/services/copilot-opportunities.ts
https://topcoder.atlassian.net/browse/PM-1373
https://topcoder.atlassian.net/browse/PM-1375
https://topcoder.atlassian.net/browse/PM-1376
https://topcoder.atlassian.net/browse/PM-1383
https://topcoder.atlassian.net/browse/PM-1380
https://topcoder.atlassian.net/browse/PM-1378
- Removed existing copilot related question
- Added duration in opportunity list
- Rephrased apply modal copy
- Added cancel copilot opportunity button in details page
- Fixed some design inconsistencies
- Fixed an issue in applications list page
=> fix(PM-1373, PM-1375, PM-1376, PM-1383, PM-1380, PM-1378): demo feedbacks implementation

.circleci/config.yml, src/apps/copilots/src/services/members.ts
https://topcoder.atlassian.net/browse/PM-1464
- Copilot applications list breaks when a copilot lacks stats
- This checks if the COPILOT is defined or not, this way undefined exception can be avoided
=> fix(PM-1464): Copilot applications list breaks when a copilot lacks stats

src/apps/talent-search/src/routes/search-results-page/SearchResultsPage.tsx
https://topcoder.atlassian.net/browse/PM-1448
- Implemented client side infinite scroll
- I tried to implement virtual list but with the two column layout, its tricky to implement it so settled with infinite scroll
- This will not improve anything on server side, the initial call is gonna take more time to load(as its going through 10000 members record to find the skills match)
=> fix(PM-1448): implemented client side infinite scroll

src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/config/copilot-details-tabs-config.ts
https://topcoder.atlassian.net/browse/PM-1470
- show applications count in tab
=> fix(PM-1470): show applications count in tab

src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/libs/ui/lib/components/form/form-groups/form-input/input-date-picker/InputDatePicker.tsx
https://topcoder.atlassian.net/browse/PM-1384
Removes the previous years and shows only current and next two years in the year dropdown of date picker
=> PM-1384 Fix date picker in copilot form

src/apps/copilots/src/copilots.routes.tsx, src/apps/copilots/src/models/CopilotOpportunity.ts, src/apps/copilots/src/models/CopilotRequest.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx, src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/CopilotRequestModal.module.scss, src/apps/copilots/src/pages/copilot-requests/copilot-request-modal/CopilotRequestModal.tsx, src/apps/copilots/src/pages/copilot-requests/index.tsx, src/apps/copilots/src/services/copilot-requests.ts
https://topcoder.atlassian.net/browse/PM-1499
=> PM-1499 edit copilot request

src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx
https://topcoder.atlassian.net/browse/PM-1496
=> Pm 1496 Show other payment type in opportunity listing

src/apps/copilots/src/models/CopilotOpportunity.ts, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx
https://topcoder.atlassian.net/browse/PM-1506
- enable apply as copilot button for user who is already a member
=> fix(PM-1506): enable apply as copilot button for user who is already a member

src/libs/ui/lib/components/table/table-functions/table.functions.ts
https://topcoder.atlassian.net/browse/PM-1526
Fixes sort on title due to missing titles in some records
=> PM-1526 Fix copilot requests sorting on title

src/apps/copilots/src/pages/copilot-opportunity-details/tabs/opportunity-details/OpportunityDetails.tsx
https://topcoder.atlassian.net/browse/PM-1489
The skills css was missing
=> PM-1489 Re-add missing css for Opportunity details page

src/apps/copilots/src/pages/copilot-request-form/index.tsx
https://topcoder.atlassian.net/browse/PM-1531
Trim form values so that blank space is not counted as character during validation
=> PM-1531 Fix: Trim form values before submit

src/apps/copilots/src/services/projects.ts
https://topcoder.atlassian.net/browse/PM-1518
Use sleep to introduce delays between chunked requests.
Sequentially fetch chunks with a delay (200ms) between requests.
=> PM-1518 Fix 429 too many requests error

src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/ConfirmModal.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/tabs/copilot-applications/CopilotApplicationAction.tsx
https://topcoder.atlassian.net/browse/PM-1610
- Show confirm modal while accepting application
=> fix(PM-1610): Show confirm modal while accepting application

src/apps/copilots/src/pages/copilot-opportunity-list/index.tsx, src/apps/copilots/src/pages/copilot-opportunity-list/styles.module.scss, src/apps/copilots/src/pages/copilot-request-form/index.tsx
https://topcoder.atlassian.net/browse/PM-1616
Adds no wrap on payment field and limits the characters to 8
=> Limit other payment type field to 8 char

src/apps/copilots/src/pages/copilot-request-form/index.tsx, src/libs/ui/lib/components/form/form-groups/form-input/input-text/InputText.tsx
https://topcoder.atlassian.net/browse/PM-1616
=> Add max length to other payment types

src/apps/review/src/lib/components/TableScorecards/TableScorecards.tsx, src/apps/review/src/pages/scorecards/ScorecardsListPage/ScorecardsListPage.tsx
https://topcoder.atlassian.net/browse/PM-1502
=> Fix pagination text and no records message

src/apps/review/src/lib/hooks/useFetchScorecard.ts, src/apps/review/src/lib/models/Scorecard.model.ts, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardDetails/ScorecardDetails.module.scss, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardDetails/ScorecardDetails.tsx, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardDetails/index.ts, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardGroups/ScorecardGroups.module.scss, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardGroups/ScorecardGroups.tsx, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardGroups/index.ts, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardSections/ScorecardSections.module.scss, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardSections/ScorecardSections.tsx, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardSections/index.ts, src/apps/review/src/pages/scorecards/ViewScorecardPage/ViewScorecardPage.module.scss, src/apps/review/src/pages/scorecards/ViewScorecardPage/ViewScorecardPage.tsx, src/apps/review/src/review-app.routes.tsx, src/libs/core/lib/router/router-context/router.context-provider.tsx
https://topcoder.atlassian.net/browse/PM-1503
- View scorecard implementation
- Integrated with backend
=> feat(PM-1503): View scorecard implementation

src/apps/copilots/src/pages/copilot-requests/CopilotRequestsPage.module.scss, src/apps/copilots/src/pages/copilot-requests/index.tsx, src/apps/copilots/src/services/copilot-requests.ts
https://topcoder.atlassian.net/browse/PM-1650
- Remove client side sorting and added server side sorting.
=> fix(PM-1650): sort from server side

src/apps/copilots/src/pages/copilot-requests/CopilotRequestsPage.module.scss, src/apps/copilots/src/pages/copilot-requests/index.tsx, src/apps/copilots/src/services/copilot-requests.ts
https://topcoder.atlassian.net/browse/PM-1614
- add white space below copilot request table
=> fix(PM-1614): add white space below copilot request table

src/apps/review/src/lib/components/ScorecardsFilter/ScorecardsFilter.module.scss, src/apps/review/src/review-app.routes.tsx
https://topcoder.atlassian.net/browse/PM-1502
=> Fixes view and css on Restricted page

src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardGroups/ScorecardGroups.module.scss, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardGroups/ScorecardGroups.tsx, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardSections/ScorecardSections.module.scss, src/apps/review/src/pages/scorecards/ViewScorecardPage/ScorecardSections/ScorecardSections.tsx
https://topcoder.atlassian.net/browse/PM-1503
- Weight column in view scorecard page
=> fix(PM-1503): Weight column in view scorecard page

src/apps/copilots/src/services/copilot-opportunities.ts
https://topcoder.atlassian.net/browse/PM-1836
- Made project optional
=> [Hot Fix]fix(PM-1836): Made project optional

src/apps/copilots/src/pages/copilot-opportunity-details/apply-opportunity-modal/ApplyOpportunityModal.tsx, src/apps/copilots/src/pages/copilot-opportunity-details/index.tsx, src/apps/copilots/src/pages/copilot-request-form/index.tsx
https://topcoder.atlassian.net/browse/PM-2168
https://topcoder.atlassian.net/browse/PM-2176
The project name was exposed to copilots earlier so we removed it from api response but it remained in the UI
Re-routing fixed
=> fix rerouting and project name exposed
